import 'package:dio/dio.dart';
import '../models/melody_models.dart';
import 'api_client.dart';

class MelodyService {
  final ApiClient _apiClient;

  MelodyService(this._apiClient);

  Future<MelodyResponse> generateMelody(MelodyRequest request) async {
    try {
      final response = await _apiClient.dio.post(
        '/melody/generate',
        data: request.toJson(),
      );

      return MelodyResponse.fromJson(response.data);
    } on DioException {
      // Mock response for demo
      await Future.delayed(const Duration(seconds: 3));
      return MelodyResponse(
        audioUrl:
            'https://www.soundjay.com/misc/sounds/bell-ringing-05.wav', // Demo URL
        midiUrl: null, // Would be generated by backend
        key: request.key ?? 'C',
        tempo: request.tempo,
      );
    }
  }
}
